name: Integración Continua

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar Node.js (ejemplo para proyectos Node)
        uses: actions/setup-node@v4
        with:
          node-version: '22.12'
      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test
